const demandesstage = [
  {
    id: 1,
    titre: "Développeur Web Front-End",
    formation: "AEC",
    formationsAutres: ["Flutter", "MongoDB"],
    competences: ["HTML", "CSS", "JS", "React", "VueJS", "Angular"],
    description: "Stage de fin d'études en développement Web Front-End",
    ville: "Saguenay",
    dateDebut: "12 avril 2021",
    dateFin: "4 juin 2021",
    nbrHeures: 35,
    type: "temps plein",
    duree: 8,
    remuneration: "À la discrétion de entreprise",
    parution: "17 mars 2021",
    infosAutres: "",
  },
  {
    id: 2,
    titre: "Développeur Web Front-End #2",
    formation: "AEC",
    formationsAutres: ["Flutter", "MongoDB"],
    competences: ["HTML", "CSS", "JS", "React", "VueJS", "Angular"],
    description: "Stage de fin d'études en développement Web Front-End",
    ville: "Saguenay",
    dateDebut: "12 avril 2021",
    dateFin: "4 juin 2021",
    nbrHeures: 35,
    type: "temps plein",
    duree: 8,
    remuneration: "à la discrétion de l'entreprise",
    parution: "17 mars 2021",
    infosAutres: "",
  },
  {
    id: 3,
    titre: "Développeur Web Front-End #3",
    formation: "AEC",
    formationsAutres: ["Flutter", "MongoDB"],
    competences: ["HTML", "CSS", "JS", "React", "VueJS", "Angular"],
    description: "Stage de fin d'études en développement Web Front-End",
    ville: "Saguenay",
    dateDebut: "12 avril 2021",
    dateFin: "4 juin 2021",
    nbrHeures: 35,
    type: "temps plein",
    duree: 8,
    remuneration: "à la discrétion de l'entreprise",
    parution: "17 mars 2021",
    infosAutres: "",
  },
  {
    id: 4,
    titre: "Développeur Web Front-End #4",
    formation: "AEC",
    formationsAutres: ["Flutter", "MongoDB"],
    competences: ["HTML", "CSS", "JS", "React", "VueJS", "Angular"],
    description: "Stage de fin d'études en développement Web Front-End",
    ville: "Saguenay",
    dateDebut: "12 avril 2021",
    dateFin: "4 juin 2021",
    nbrHeures: 35,
    type: "temps plein",
    duree: 8,
    remuneration: "à la discrétion de l'entreprise",
    parution: "17 mars 2021",
    infosAutres: "",
  },
  {
    id: 5,
    titre: "Développeur Web Front-End #5",
    formation: "AEC",
    formationsAutres: ["Flutter", "MongoDB"],
    competences: ["HTML", "CSS", "JS", "React", "VueJS", "Angular"],
    description: "Stage de fin d'études en développement Web Front-End",
    ville: "Saguenay",
    dateDebut: "12 avril 2021",
    dateFin: "4 juin 2021",
    nbrHeures: 35,
    type: "temps plein",
    duree: 8,
    remuneration: "à la discrétion de l'entreprise",
    parution: "17 mars 2021",
    infosAutres: "",
  },
];
/*
    offres: [
      {
        id: 1,
        titre: "stagiaire Web Front-End",
        entreprise: "TLM",
        secteurActivite: "WEB",
        ville: "Saguenay",
        dateDebut: "12 avril 2021",
        duree: 8,
        description: "Stage de fin d'études en développement Web Front-End",
        nbrHeures: 35,
        competences: ["HTML", "CSS", "JS", "React", "VueJS", "Angular"],
        remuneration: "oui",
        possibiliteEmploi: "oui",
        parution: "17 mars 2021",
        infosAutres: "",
      },
    ],
  },*/

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  demandesstage,
};
